SCR_PlayerCommandsConfig {
 m_aCommands {
  KK_GarrisonCommand "{6A696943F5FFABA4}" {
   m_sCommandName "KK_Garrison"
   m_sCommandDisplayName "Garrison"
   m_sImageset "{A4A692135635424E}UI/Imagesets/Commanding/Commanding_Icons.imageset"
   m_sIconName "kick"
   m_bShowOnMap 1
   m_iGestureID 4
   m_bShowPreview 1
   m_bPlayAIResponse 0
   m_sWaypointPrefab "{6A6969C011223344}Prefabs/AI/Waypoints/KK_AIWaypoint_GarrisonBuilding.et"
  }
  KK_ClearCommand "{6A69694EF655681E}" {
   m_sCommandName "KK_Clear"
   m_sCommandDisplayName "Clear Building"
   m_sImageset "{A4A692135635424E}UI/Imagesets/Commanding/Commanding_Icons.imageset"
   m_sIconName "kick"
   m_bShowOnMap 1
   m_iGestureID 4
   m_bShowPreview 1
   m_bPlayAIResponse 0
   m_sWaypointPrefab "{14477E232372F43A}Prefabs/AI/Waypoints/KK_AIWaypoint_ClearBuilding.et"
  }
 }
}