SCR_PlayerCommandingMenuConfig {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{5A4ED511170B5C06}" {
  m_aElements {
   SCR_PlayerCommandingMenuCommand "{6A69694370E99A10}" {
    m_sCommandName "KK_Garrison"
   }
   SCR_PlayerCommandingMenuCommand "{6A69694EA9F1449F}" {
    m_sCommandName "KK_Clear"
   }
  }
 }
}