SCR_PlayerCommandingMenuConfig {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{5A4ED511170B5C06}" {
  m_aElements {
   SCR_PlayerCommandingMenuCommand "{6A69694370E99A10}" {
    m_sCommandName "KK_Garrison"
   }
   SCR_PlayerCommandingMenuCommand "{6A69694EA9F1449F}" {
    m_sCommandName "KK_Clear"
   }
   SCR_PlayerCommandingMenuCategoryElement "{6A7A020100000040}" {
    m_sCategoryDisplayText "Nodes"
    m_sImageset "{A4A692135635424E}UI/Imagesets/Commanding/Commanding_Icons.imageset"
    m_sIconName "kick"
    m_aElements {
     SCR_PlayerCommandingMenuCommand "{6A7A020100000041}" {
      m_sCommandName "KK_WP_AddNode"
     }
     SCR_PlayerCommandingMenuCommand "{6A7A020100000042}" {
      m_sCommandName "KK_WP_DeleteNode"
     }
     SCR_PlayerCommandingMenuCommand "{6A7A020100000043}" {
      m_sCommandName "KK_WP_DeleteCluster"
     }
     SCR_PlayerCommandingMenuCommand "{6A7A020100000044}" {
      m_sCommandName "KK_WP_Undo"
     }
    }
   }
   SCR_PlayerCommandingMenuCategoryElement "{6A7A020100000001}" {
    m_sCategoryDisplayText "WP Author"
    m_sImageset "{A4A692135635424E}UI/Imagesets/Commanding/Commanding_Icons.imageset"
    m_sIconName "kick"
    m_aElements {
     SCR_PlayerCommandingMenuCommand "{6A7A020100000010}" {
      m_sCommandName "KK_WP_Lock"
     }
     SCR_PlayerCommandingMenuCommand "{6A7A020100000011}" {
      m_sCommandName "KK_WP_Window"
     }
     SCR_PlayerCommandingMenuCommand "{6A7A020100000012}" {
      m_sCommandName "KK_WP_Door"
     }
     SCR_PlayerCommandingMenuCommand "{6A7A020100000013}" {
      m_sCommandName "KK_WP_Post"
     }
     SCR_PlayerCommandingMenuCommand "{6A7A020100000014}" {
      m_sCommandName "KK_WP_Route"
     }
     SCR_PlayerCommandingMenuCommand "{6A7A020100000016}" {
      m_sCommandName "KK_WP_Delete"
     }
     SCR_PlayerCommandingMenuCommand "{6A7A020100000031}" {
      m_sCommandName "KK_WP_Undo"
     }
     SCR_PlayerCommandingMenuCommand "{6A7A020100000015}" {
      m_sCommandName "KK_WP_Debug"
     }
     SCR_PlayerCommandingMenuCategoryElement "{6A7A020100000020}" {
      m_sCategoryDisplayText "Building"
      m_sImageset "{A4A692135635424E}UI/Imagesets/Commanding/Commanding_Icons.imageset"
      m_sIconName "kick"
      m_aElements {
       SCR_PlayerCommandingMenuCommand "{6A7A020100000021}" {
        m_sCommandName "KK_WP_Cache"
       }
       SCR_PlayerCommandingMenuCommand "{6A7A02010000002A}" {
        m_sCommandName "KK_WP_Roof"
       }
       SCR_PlayerCommandingMenuCommand "{6A7A020100000022}" {
        m_sCommandName "KK_WP_Floor0"
       }
       SCR_PlayerCommandingMenuCommand "{6A7A020100000023}" {
        m_sCommandName "KK_WP_Floor1"
       }
       SCR_PlayerCommandingMenuCommand "{6A7A020100000024}" {
        m_sCommandName "KK_WP_Floor2"
       }
       SCR_PlayerCommandingMenuCommand "{6A7A020100000025}" {
        m_sCommandName "KK_WP_Floor3"
       }
       SCR_PlayerCommandingMenuCommand "{6A7A020100000026}" {
        m_sCommandName "KK_WP_Floor4"
       }
       SCR_PlayerCommandingMenuCommand "{6A7A020100000027}" {
        m_sCommandName "KK_WP_Floor5"
       }
       SCR_PlayerCommandingMenuCommand "{6A7A020100000028}" {
        m_sCommandName "KK_WP_Floor6"
       }
       SCR_PlayerCommandingMenuCommand "{6A7A020100000029}" {
        m_sCommandName "KK_WP_Floor7"
       }
      }
     }
    }
   }
  }
 }
}
