ActionManager : "{795184CF9AD764DB}Configs/System/chimeraInputCommon.conf" {
 Actions +{
  Action KK_CQBOrderGarrison {
   InputSource InputSourceValue "{6A7B0A1000000060}" {
    Input "keyboard:KC_NUMPAD1"
    Filter InputFilterDown "{6A7B0A1000000061}" {
    }
   }
  }
  Action KK_CQBOrderClear {
   InputSource InputSourceValue "{6A7B0A1000000062}" {
    Input "keyboard:KC_NUMPAD2"
    Filter InputFilterDown "{6A7B0A1000000063}" {
    }
   }
  }
  Action KK_CQBOrderAdvance {
   InputSource InputSourceValue "{6A7B0A1000000064}" {
    Input "keyboard:KC_NUMPAD3"
    Filter InputFilterDown "{6A7B0A1000000065}" {
    }
   }
  }
  Action KK_CQBOrderBound {
   InputSource InputSourceValue "{6A7B0A1000000066}" {
    Input "keyboard:KC_NUMPAD4"
    Filter InputFilterDown "{6A7B0A1000000067}" {
    }
   }
  }
  Action KK_CQBOrderTakeCover {
   InputSource InputSourceValue "{6A7B0A1000000068}" {
    Input "keyboard:KC_NUMPAD5"
    Filter InputFilterDown "{6A7B0A1000000069}" {
    }
   }
  }
 }
 Contexts +{
  ActionContext KK_CQBOrderContext {
   Priority 2000
   Flags 0x2 0
   ActionRefs {
    "KK_CQBOrderGarrison"
    "KK_CQBOrderClear"
    "KK_CQBOrderAdvance"
    "KK_CQBOrderBound"
    "KK_CQBOrderTakeCover"
   }
  }
 }
}
