SCR_EditorActionList {
 m_Actions {
  SCR_WaypointBaseCommandAction "{54B4A9AB204E8C1E}" {
   m_ActionGroup COMMAND_TASK
  }
  KK_GarrisonCommandAction "{6A696941DD0BF3A6}" {
   m_Info SCR_UIInfo "{6A696941C4BD964E}" {
    Name "Garrison Building"
    Description "Occupy interior positions in the nearest building"
    Icon "{8083D425A749EE46}UI/Textures/Editor/Toolbar/Commanding/Toolbar_Commanding_Objective_Custom.edds"
   }
   m_ActionGroup COMMAND_TASK
   m_CommandPrefab "{6A6969C055667788}PrefabsEditable/Auto/AI/Waypoints/E_KK_AIWaypoint_GarrisonBuilding.et"
  }
  KK_ClearCommandAction "{6A696947AA2BCB61}" {
   m_Info SCR_UIInfo "{6A69694712B2A2D5}" {
    Name "Clear Building"
    Description "Search and clear the building nearest this position"
    Icon "{36106BA9CF5483B0}UI/Textures/Editor/Toolbar/Commanding/Toolbar_Commanding_Waypoint_Attack.edds"
   }
   m_ActionGroup COMMAND_TASK
   m_CommandPrefab "{BFB02E608EDD10FB}PrefabsEditable/Auto/AI/Waypoints/E_KK_AIWaypoint_ClearBuilding.et"
  }
 }
}